#!/bin/bash
AVAIL_GPUS=$(qstat -f | grep BIP | grep -v 'test' | grep '0/0/80' | grep -v 80\/ |grep -v ' d' | grep -v test | wc | sed -e 's/^\s*//' | sed -e 's/\s.*//')
UNRESERVED=$(qstat -f | grep BIP | grep -v 'test' | grep '0/0/80' |grep -v ' d' | grep -v test | wc | sed -e 's/^\s*//' | sed -e 's/\s.*//')


echo "Available nodes: $AVAIL_GPUS"
echo "Reserved nodes: $(($UNRESERVED-$AVAIL_GPUS))"
echo "Reserved nodes being used: $(qstat -f | grep BIP | grep -v 'test' | grep '80/80/80' |grep -v ' d' | grep -v test | wc -l)"
